# Generated by Django 6.0.3 on 2026-05-10 08:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Token"),
        ),
    ]
