# Generated by Django 6.0.3 on 2026-04-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, verbose_name="Название статьи")),
                ("content", models.TextField(max_length=1000, verbose_name="Тело контента")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/images", verbose_name="Фото публикации"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время публикации")),
                ("is_active", models.BooleanField(default=False, verbose_name="Статус публикации")),
                ("views_count", models.IntegerField(default=0, verbose_name="Счетчик просмотров")),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["created_at"],
            },
        ),
    ]
