# Generated by Django 6.0.3 on 2026-05-01 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Blog",
            new_name="Article",
        ),
    ]
