# Generated by Django 6.0.3 on 2026-04-03 18:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Название категории")),
                (
                    "description",
                    models.TextField(help_text="Введите описание категории", verbose_name="Описание категории"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название продукта", max_length=100, verbose_name="Название продукта"
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Введите описание продукта", verbose_name="Описание продукта"),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Загрузка фото продукта", upload_to="products/photos", verbose_name="Фото продукта"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Цена продукта")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания продукта")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата изменения продукта")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
        ),
    ]
