# Generated by Django 6.0.3 on 2026-04-03 18:44

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="Введите описание категории", null=True, verbose_name="Описание категории"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="Введите описание продукта", null=True, verbose_name="Описание продукта"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузка фото продукта",
                null=True,
                upload_to="products/photos",
                verbose_name="Фото продукта",
            ),
        ),
    ]
