# Generated by Django 6.0.3 on 2026-05-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="Счетчик просмотров"),
        ),
    ]
