# Generated by Django 6.0.3 on 2026-05-12 16:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_views_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="published",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
