# Generated by Django 6.0.3 on 2026-05-12 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options_product_published"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="published",
            new_name="publish",
        ),
    ]
