# Generated by Django 6.0.3 on 2026-04-04 11:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Адрес"),
        ),
    ]
