# Generated by Django 6.0.3 on 2026-05-12 19:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_published_product_publish"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="publish",
        ),
        migrations.AddField(
            model_name="product",
            name="published",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
