# Generated by Django 6.0.3 on 2026-05-20 23:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name="URL-слаг"),
        ),
    ]
