# Generated by Django 6.0.3 on 2026-05-20 23:22

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="temp", max_length=255, unique=True, verbose_name="URL-слаг"),
            preserve_default=False,
        ),
    ]
